Repository Anxinal/CyberCatCafe, pull requests merged in 2025-06, with the labels that each got.

#15 [Feature] UI imporvement and more organised codebase for the login and register system
  CyberCatMain/app/_layout.tsx
  CyberCatMain/app/account/AccountReusableComponents.tsx
  CyberCatMain/app/account/register.jsx
  CyberCatMain/app/account/userInfo.js
  CyberCatMain/app/index.jsx
  CyberCatMain/assets/images/cat-logo.png
  CyberCatMain/components/ToastMessage.js
  CyberCatMain/constants/Colors.ts
  CyberCatMain/constants/ReusableStyles.ts
  CyberCatMain/constants/UserInitialInfo.js
  CyberCatMain/package-lock.json
  CyberCatMain/tsconfig.json
Labels: enhancement

#6 [Feature] Basic Structure of Achievement Page
  CyberCatMain/app/_layout.tsx
  CyberCatMain/app/account/register.jsx
  CyberCatMain/app/index.jsx
  CyberCatMain/app/mainPages/Achievement/achievement.jsx
  CyberCatMain/app/mainPages/_layout.tsx
  CyberCatMain/app/mainPages/achievement.jsx
  CyberCatMain/app/mainPages/explore.tsx
  CyberCatMain/app/mainPages/index.tsx
  CyberCatMain/constants/Colors.ts
  CyberCatMain/constants/achievementList.js
  CyberCatMain/tsconfig.json
Labels: enhancement

#30 [Extension]Update Achievement UI and Implement basic achievement trigger mechanism
  CyberCatMain/app/account/userInfo.js
  CyberCatMain/app/mainPages/Achievement/achievement.js
  CyberCatMain/app/mainPages/Achievement/screen.jsx
  CyberCatMain/components/StatusDisplay.tsx
  CyberCatMain/constants/AchievementStyles.ts
  CyberCatMain/constants/IconList.js
  CyberCatMain/constants/achievementList.js
Labels: enhancement, Extension

#31 [Feature] Achievement system and the search function
  CyberCatMain/app/mainPages/Achievement/achievement.js
  CyberCatMain/app/mainPages/Achievement/screen.jsx
  CyberCatMain/constants/IconList.js
  CyberCatMain/constants/achievementList.js
Labels: Extension
