Repository Anxinal/CyberCatCafe, pull requests merged in 2025-07, with the labels that each got.

#34 [Feature] Outline the design the front end pages
  .gitignore
  CyberCatMain/app/account/UserPanel.jsx
  CyberCatMain/app/account/userInfo.js
  CyberCatMain/app/mainPages/Ranking/RankingDisplayComp.jsx
  CyberCatMain/app/mainPages/Ranking/UserRankingCard.jsx
  CyberCatMain/app/mainPages/Ranking/screen.jsx
  CyberCatMain/app/mainPages/Timer/TimerNotification.js
  CyberCatMain/app/mainPages/Timer/screen.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/FriendInbox.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/FriendList.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/FriendRanking.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/RankingParticipant.ts
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/Screen.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/SearchList.jsx
  CyberCatMain/app/mainPages/UserCenter/settingsConfig.js
  CyberCatMain/components/FriendNoti.tsx
  CyberCatMain/components/IconButton.jsx
  CyberCatMain/constants/IconList.js
  CyberCatMain/constants/RankingNames.js
  CyberCatMain/constants/UserInitialInfo.js
  CyberCatMain/data/SendFriendRequest.ts
  CyberCatMain/data/TimerConvert.ts
  CyberCatMain/data/UserRankInfo.js
  package-lock.json
Labels: Extension

#36 [Debug] Allow the app to run on android VM
  .gitignore
  CyberCatMain/app.json
  CyberCatMain/app/account/userInfo.js
  CyberCatMain/app/index.jsx
  CyberCatMain/app/mainPages/Achievement/achievement.js
  CyberCatMain/constants/AccountStyles.ts
  CyberCatMain/firebaseConfig.js
  CyberCatMain/package-lock.json
  CyberCatMain/package.json
Labels: bug

#32 [Feature] A functional cat raising system
  CyberCatMain/.gitignore
  CyberCatMain/app/account/petInfo.js
  CyberCatMain/app/account/userInfo.js
  CyberCatMain/app/mainPages/CatCafe/Cafe.jsx
  CyberCatMain/app/mainPages/CatCafe/Cat.tsx
  CyberCatMain/app/mainPages/CatCafe/catFoodCan.jsx
  CyberCatMain/app/mainPages/CatCafe/screen.jsx
  CyberCatMain/assets/images/CatGif.gif
  CyberCatMain/assets/images/CatWalking.gif
  CyberCatMain/assets/images/cafe-background.jpg
  CyberCatMain/assets/images/catBowl.png
  CyberCatMain/assets/images/heartIcon.png
  CyberCatMain/constants/InventoryList.js
  CyberCatMain/constants/UserInitialInfo.js
  CyberCatMain/data/Inventory.js
  CyberCatMain/package-lock.json
  CyberCatMain/package.json
  package.json
Labels: enhancement

#42 [Feature]The stats system
  CyberCatMain/app/mainPages/Stats/BarChartDisplay.tsx
  CyberCatMain/app/mainPages/Stats/CalendarDisplay.tsx
  CyberCatMain/app/mainPages/Stats/Screen.jsx
  CyberCatMain/app/mainPages/Stats/Testing.ts
  CyberCatMain/app/mainPages/UserCenter/screen.tsx
  CyberCatMain/app/mainPages/_layout.tsx
  CyberCatMain/constants/HourToDotColor.ts
  CyberCatMain/constants/IconList.js
  CyberCatMain/data/FocusStats.ts
  CyberCatMain/package-lock.json
  CyberCatMain/package.json
  package-lock.json
Labels: Extension

#45 [Debug] Fix bugs occurred in testing of pet system and stats system
  CyberCatMain/app/account/petInfo.js
  CyberCatMain/app/mainPages/Achievement/achievement.js
  CyberCatMain/app/mainPages/Achievement/screen.jsx
  CyberCatMain/app/mainPages/CatCafe/Cafe.jsx
  CyberCatMain/app/mainPages/CatCafe/catFoodCan.jsx
  CyberCatMain/app/mainPages/Stats/Screen.jsx
  CyberCatMain/app/mainPages/Timer/TimeView.tsx
  CyberCatMain/app/mainPages/Timer/screen.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/CatShop.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/DisplaySettings.jsx
  CyberCatMain/app/mainPages/UserCenter/Settings/Friend/Screen.jsx
  CyberCatMain/app/mainPages/UserCenter/settingsConfig.ts
  CyberCatMain/app/mainPages/_layout.tsx
  CyberCatMain/constants/TimerStyles.ts
  CyberCatMain/data/FocusStats.ts
  CyberCatMain/data/Inventory.js
  CyberCatMain/package-lock.json
  CyberCatMain/package.json
  package-lock.json
  package.json
Labels: bug

#46 [Debug]Update more UI settings
  CyberCatMain/app/mainPages/Stats/CalendarDisplay.jsx
  CyberCatMain/app/mainPages/Stats/CalendarDisplay.tsx
  CyberCatMain/app/mainPages/_layout.tsx
  CyberCatMain/constants/UserInitialInfo.js
  CyberCatMain/data/FocusStats.ts
Labels: bug
